baseURL: "https://pestpolicy.com/"
languageCode: "en-us"
title: "Insights" # Updated for SEO
theme: 'hugo-PaperMod'

outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  sitemap: ["XML"]

outputFormats:
  XML:
    name: "Sitemap"
    mediaType: "application/xml"
    baseName: "sitemap"
    isPlainText: true
    notAlternative: true

# config.yml example (merge with your existing config)
theme: PaperMod

params:
  # Demo-specific settings
  defaultTheme: auto
  disableSpecial1stPost: false
  disableScrollToTop: false
  homeInfoParams:
    Title: "Hi, I'm PaperMod"
    Content: "This is the demo content from PaperMod theme"

# Enable features used in the demo
buildDrafts: true
buildFuture: true
buildExpired: true

taxonomies:
  tag: 'tags'
  category: 'categories'

permalinks:
  posts: "/:slug/" # Keeping your exact structure
slug:
  ugly: false # Preserved

params:
  env: 'production'
  defaultTheme: 'auto'

  title: "Insights | Bugs, Paints, Sprayers"
  description: "Trusted step-by-step DIY Home Improvmeent guides and unbiased product reviews."
  robots: "index, follow"

  analytics:
    google:
      SiteVerificationTag: "wcIIamJKWxC3IcPXe02IZlAEWcGk828ZThxeK1w3aUQ" # Nested under analytics.google
    anonymizeIP: true # This should likely be at the same level as 'google' if it's a general analytics setting

  imaging:
    quality: 85
    webp: true

build:
  errorOnMissingPagePermalinks: true
  errorOnInvalidPermalinks: true
  writeStats: true
  useResourceCacheWhen: "always" # Speeds up builds
  noChmod: true

sitemap:
  changefreq: "weekly"
  priority: 0.7
  filename: "sitemap.xml"
  taxonomies: []
  disable: false