baseURL: "https://pestpolicy.com/"
languageCode: "en-us"
title: "Home Guides"
theme: 'hugo-PaperMod'

enableRobotsTXT: true
enableSitemap: true

outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  sitemap: ["XML"]

outputFormats:
  XML:
    name: "Sitemap"
    mediaType: "application/xml"
    baseName: "sitemap"
    isPlainText: true
    notAlternative: true

buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  tag: 'tags'
  category: 'categories'

permalinks:
  posts: "/:slug/"

slug:
  ugly: false

params:
  env: 'production'
  defaultTheme: 'auto'
  disableSpecial1stPost: false
  disableScrollToTop: false

  title: "Home Improvement Guides"
  description: "Guides for Pest solutions, sprayers and paint. Visit the [Product Reviews](/categories/product-reviews/) or check out the [DIY Guides](/categories/guide/)"
  robots: "index, follow"

  homeInfoParams:
    Title: "Home Improvement | Bugs, Paint, & Shoes"
    Content: |
      Welcome to Pestpolicy. Insights into bugs control, DIY painting, and Shoes - reveal how pests can affect painted surfaces and the performance of spray equipment. Understanding the interaction between paint types and sprayer technology is essential for achieving smooth, durable finishes.

      Proper maintenance of sprayers and selecting the right paint formulation can also minimize issues caused by bugs during and after application.
      Visit the [Product Reviews](/categories/product-reviews/) or check out the [DIY Guides](/categories/guide/).

  analytics:
    google:
      SiteVerificationTag: "wcIIamJKWxC3IcPXe02IZlAEWcGk828ZThxeK1w3aUQ"

  anonymizeIP: true

  imaging:
    quality: 85
    webp: true

sitemap:
  changefreq: "weekly"
  priority: 0.7
  filename: "sitemap.xml"
  disable: false

build:
  errorOnMissingPagePermalinks: true
  errorOnInvalidPermalinks: true
  writeStats: true
  useResourceCacheWhen: "always"
  noChmod: true

menu:
  main:
    - name: Blog
      url: /posts/
      weight: 1
    - name: Fleas
      url: /categories/fleas/
      weight: 2
    - name: Product Reviews
      url: /categories/product-reviews/
      weight: 3
    - name: Guides
      url: /categories/guide/
      weight: 4
